version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  BeforeInstall:
    - location: scripts/stop_nginx.sh
      timeout: 300
      runas: root
  AfterInstall:
    - location: scripts/start_nginx.sh
      timeout: 300
      runas: root
  ApplicationStart:
    - location: scripts/restart_app.sh
      timeout: 300
      runas: root

